controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
app_register:
    path: /register
    controller: App\Controller\UserAuthSecurityController::register
app_homepage:
    path: /homepage
    controller: App\Controller\HomeController::homepage
