controllers:
    resource: ../src/Controller/
    type: annotation
index:
    path: /
    controller: App\Controller\HomeController::welcome
kernel:
    resource: ../src/Kernel.php
    type: annotation
app_register:
    path: /register
    controller: App\Controller\UserAuthSecurityController::register
app_homepage:
    path: /homepage
    controller: App\Controller\HomeController::homepage
create_post:
    path: /create-post
    controller: App\Controller\PostController::createPost
#app_admin_page:
#    path: manager/users-list
#    controller: App\Controller\AdminController::adminpage
#user_edit:
#    path: /user/{id}/edit
#    controller: App\Controller\AdminController::adminpage
#user_delete:
#    path: /admin/users/{id}/delete
#    controller: App\Controller\AdminController::adminpage
user_toggle:
    path: /manager/users/{id}/ban
    controller: App\Controller\AdminController::adminpage


